name: Go

on: [push]

jobs:

  build_plugin:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2

      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

  unit_tests:
    name: Test and coverage
    runs-on: ubuntu-latest
    needs:
      - build_plugin
    steps:

    - uses: actions/checkout@v2
  
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    
    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  functional_tests:
    name: Run Functional Tests
    runs-on: ubuntu-latest
    needs:
      - build_plugin
    strategy:
      matrix:
        tags:
          - "@kuma_roles"
    steps:

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Setup Functional Tests
      run: |
        curl https://shipyard.run/install | bash

    - name: Run Functional Tests
      run: |
        make build
        cd functional_tests && go run . --godog.tags="${{ matrix.tags }}"
