name: Go

on: [push]

jobs:

  build_plugin:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2

      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

  unit_tests:
    name: Test and coverage
    runs-on: ubuntu-latest
    needs:
      - build_plugin
    steps:

    - uses: actions/checkout@v2
  
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    
    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  functional_tests:
    name: Run Functional Tests
    runs-on: ubuntu-latest
    needs:
      - build_plugin
    strategy:
      matrix:
        tags:
          - "@kuma_roles"
          - "@kuma_dataplane_token"
          - "@kuma_dataplane_token_globbed"
          - "@kuma_user_token"
    steps:

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Setup Functional Tests
      run: |
        curl https://shipyard.run/install | bash

    - name: Run Functional Tests
      run: |
        make build
        cd functional_tests && go run . --godog.tags="${{ matrix.tags }}"

  create_artifacts:
    name: Create and upload artifacts
    runs-on: ubuntu-latest
    needs:
      - functional_tests
    steps:
    
      - uses: actions/checkout@v2
    
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      
      - name: Build multiple versions
        run: make build_all

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plugin_binaries
          path: |
            bin/vault-plugin-kuma-darwin-arm64
            bin/vault-plugin-kuma-darwin_amd64
            bin/vault-plugin-kuma-linux-amd64
            bin/vault-plugin-kuma-linux-arm64
            bin/vault-plugin-kuma-windows-amd64.exe
